function skillsMember() {
  return [
    { name: 'HTML', level: 100 },
    { name: 'CSS', level: 100 },
    { name: 'JavaScript', level: 100 },
    { name: 'React', level: 100 },
    { name: 'Node.js', level: 100 },
    { name: 'Express.js', level: 100 },
    { name: 'MongoDB', level: 100 },
    { name: 'Git', level: 100 },
    { name: 'GitHub', level: 100 },
    { name: 'Heroku', level: 100 },
    { name: 'Netlify', level: 100 },
    { name: 'Figma', level: 100 },
    { name: 'Photoshop', level: 100 },
    { name: 'Illustrator', level: 100 },
    { name: 'After Effects', level: 100 },
    { name: 'Premiere Pro', level: 100 },
    { name: 'XD', level: 100 },
    { name: 'InDesign', level: 100 },
    { name: 'Lightroom', level: 100 },
    { name: 'Audition', level: 100 },
    { name: 'Bridge', level: 100 },
    { name: 'Animate', level: 100 },
    { name: 'Dreamweaver', level: 100 },
    { name: 'Acrobat', level: 100 },
    { name: 'Media Encoder', level: 100 },
    { name: 'Character Animator', level: 100 },
    { name: 'Prelude', level: 100 },
    { name: 'Spark', level: 100 },
    { name: 'Rush', level: 100 },
    { name: 'Dimension', level: 100 },
    { name: 'InCopy', level: 100 },
    { name: 'Lightroom Classic', level: 100 },
    { name: 'Fuse', level: 100 },
    { name: 'Captivate', level: 100 },
    { name: 'Project Felix', level: 100 },
    { name: 'Character Animator', level: 100 },
    { name: 'Audition', level: 100 },
    { name: 'Prelude', level: 100 },
    { name: 'Spark', level: 100 }
    ];
}